# Generated by Django 5.0.6 on 2025-03-27 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='conversationmessage',
            old_name='create_by',
            new_name='created_by',
        ),
    ]
