# Generated by Django 5.0.6 on 2025-03-18 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='property',
            old_name='tittle',
            new_name='title',
        ),
    ]
